### ISSUE TITLE
Support converting OMI audio emitter gltf to glb.

### ISSUE THREAD

**Issue by fire** [omigroup/omi-gltf-transform#4]
Support converting OMI audio emitter gltf to glb because no other tool understands OMI yet.

**Comment by fire** [comment]
Errors.

```
./omi-gltf-transform.js ../../OMI_audio_emitter-simple.gltf ../../OMI_audio_emitter-simple.glb
file:///home/ernestlee/Documents/groups-workspace-fire/gltf_sandbox/omi_audio_emitter/simple/omi-gltf-transform/src/extensions/MOZ_hubs_components.js:95
    const extension = propertyDef.extensions?.[MOZ_HUBS_COMPONENTS];
```

```
$ npx omi-gltf-transform ../OMI_audio_emitter-simple.gltf ../OMI_audio_emitter-simple.glb
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'fs' imported from /home/ernestlee/.local/lib/node_modules/omi-gltf-transform/bin/omi-gltf-transform.js
    at packageResolve (internal/modules/esm/resolve.js:664:9)
    at moduleResolve (internal/modules/esm/resolve.js:705:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:798:11)
    at Loader.resolve (internal/modules/esm/loader.js:100:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:246:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:47:40)
    at link (internal/modules/esm/module_job.js:46:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
npm ERR! code 1
npm ERR! path /home/ernestlee/Documents/groups-workspace-fire/gltf_sandbox/omi_audio_emitter/simple/omi-gltf-transform
npm ERR! command failed
npm ERR! command sh -c omi-gltf-transform "../OMI_audio_emitter-simple.gltf" "../OMI_audio_emitter-simple.glb"

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ernestlee/.npm/_logs/2022-02-05T04_35_57_346Z-debug.log

```
